Repository WildCodeSchool/orleans-php-2003-project-izycontrat, pull requests merged in 2020-07, with the labels that each got.

#114 Us70 edit article
  src/Controller/ArticleController.php
  src/Entity/User.php
  templates/article/edit.html.twig
Labels: Reviewed

#115 fix blog
  assets/scss/app.scss
  src/Controller/ArticleController.php
  src/DataFixtures/ArticleFixtures.php
  templates/_layout.html.twig
  templates/article/blog.html.twig
  templates/article/index.html.twig
Labels: Reviewed

#116 Us71 delete article
  src/Controller/ArticleController.php
  templates/article/_delete_form.html.twig
  templates/article/edit.html.twig
  templates/article/index.html.twig
Labels: Reviewed

#117 View client
  assets/scss/app.scss
  assets/scss/clientsList.scss
  config/packages/security.yaml
  src/Controller/DashboardController.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/PersonFixtures.php
  src/Twig/PhoneExtension.php
  templates/dashboard/Admin/client.html.twig
  templates/dashboard/Admin/show.html.twig
Labels: Reviewed

#119 fixNavbar
  assets/scss/Molecules/_navbar.scss
  symfony.lock
  templates/_navbar.html.twig
Labels: Reviewed

#123 addFavicon - s/o Oleg
  public/images/favicon/android-chrome-192x192.png
  public/images/favicon/android-chrome-512x512.png
  public/images/favicon/apple-touch-icon.png
  public/images/favicon/browserconfig.xml
  public/images/favicon/favicon-16x16.png
  public/images/favicon/favicon-32x32.png
  public/images/favicon/favicon.ico
  public/images/favicon/mstile-150x150.png
  public/images/favicon/site.webmanifest
  templates/base.html.twig
Labels: Reviewed

#118 US24 / AddLawyerList
  assets/scss/lawyersList.scss
  src/Controller/LawyerController.php
  src/DataFixtures/PersonFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Person.php
  src/Repository/UserRepository.php
  templates/lawyer/index.html.twig
  webpack.config.js
Labels: Reviewed

#124 Us10 view article
  assets/js/blog.js
  assets/scss/article.scss
  assets/scss/blog.scss
  src/Controller/ArticleController.php
  src/Entity/Article.php
  src/Repository/ArticleRepository.php
  templates/_footer.html.twig
  templates/article/blog.html.twig
  templates/article/index.html.twig
  webpack.config.js
Labels: Corrections done

#125 Us11 view article in details
  assets/scss/article.scss
  templates/article/index.html.twig
  templates/article/show.html.twig
Labels: Reviewed

#126 Remove Title on picture
  templates/home/index.html.twig
Labels: Reviewed

#130 fixHome
  templates/security/login.html.twig
Labels: Reviewed

#129 Fix_article_image_edit
  src/Entity/Article.php
  templates/article/edit.html.twig
  templates/article/new.html.twig
Labels: Reviewed

#131 D2M 03/07
  src/Entity/Article.php
  templates/article/edit.html.twig
  templates/article/new.html.twig
  templates/security/login.html.twig
Labels: Dev to master

#134 Fix favicon route
  symfony.lock
  templates/base.html.twig
Labels: Reviewed

#136 Us46 lawyer registration
  src/Controller/RegistrationController.php
  src/Entity/Person.php
  src/Form/RegistrationLawyerType.php
  src/Form/RegistrationUserType.php
  templates/_footer.html.twig
  templates/registration/lawyer.html.twig
  templates/registration/user.html.twig
Labels: Reviewed

#139 Us26 add client profile informations
  assets/scss/dashboardPage.scss
  src/Controller/DashboardController.php
  src/DataFixtures/PersonFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/_layout.html.twig
  templates/dashboard/index.html.twig
  templates/dashboard/profile.html.twig
  webpack.config.js
Labels: Reviewed

#141 Creation de document et Fix du formulaire de Registration
  assets/css/app.css
  assets/scss/dashboard.scss
  assets/scss/document.scss
  assets/scss/editor.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/routes.yaml
  config/routes/js_translation.yaml
  config/services.yaml
  package-lock.json
  package.json
  public/uploads/documents/Statut-SASU_5f0506f24ed05.html.twig
  src/Controller/DashboardController.php
  src/Controller/DocumentController.php
  src/Controller/RegistrationController.php
  src/Entity/Document.php
  src/Entity/Person.php
  src/Entity/User.php
  src/Form/DocumentType.php
  src/Repository/DocumentRepository.php
  symfony.lock
  templates/_layout.html.twig
  templates/base.html.twig
  templates/document/editor.html.twig
  templates/document/index.html.twig
  translations/messages.fr.yaml
  webpack.config.js
  yarn.lock
Labels: Reviewed

#143 ajout de la fonction d'ajout de champs en fonction des entitées
  assets/js/fields.js
  assets/scss/_vars.scss
  config/packages/fos_ckeditor.yaml
  config/packages/security.yaml
  config/packages/twig.yaml
  package.json
  public/uploads/documents/Statut-SASU_5f0506f24ed05.html.twig
  src/Controller/DocumentController.php
  src/Controller/FieldController.php
  src/Entity/Document.php
  src/Entity/Field.php
  src/Form/DocumentType.php
  src/Form/FieldType.php
  src/Repository/FieldRepository.php
  templates/_layout.html.twig
  templates/base.html.twig
  templates/dashboard/Admin/document/editor.html.twig
  templates/dashboard/Admin/document/index.html.twig
  templates/dashboard/Admin/field/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Corrections done, Reviewed

#144 Us48 lawyer profil information
  assets/scss/Molecules/_navbar.scss
  assets/scss/dashboardPage.scss
  src/Controller/DashboardController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/PersonFixtures.php
  src/Form/ClientType.php
  src/Form/EditUserType.php
  src/Form/LawyerType.php
  templates/_navbar.html.twig
  templates/dashboard/index.html.twig
  templates/dashboard/profile.html.twig
Labels: Reviewed

#145 ajout fonction pour supprimer un document
  src/Controller/DocumentController.php
  templates/dashboard/Admin/document/index.html.twig
  templates/document/_delete_form.html.twig
Labels: Corrections done, Reviewed

#146 fix form
  config/packages/twig.yaml
  templates/dashboard/profile.html.twig
Labels: Reviewed

#147 fix lawyer specialization
  src/Form/LawyerType.php
Labels: Reviewed

#149 Update README.md
  README.md
Labels: Corrections done, Reviewed

#151 Downgrade to PHP 7.2
  README.md
  composer.lock
  config/packages/doctrine_migrations.yaml
  symfony.lock
Labels: Reviewed

#176 Correction du bouton deconexion
  assets/scss/Molecules/_navbar.scss
  src/Entity/Person.php
  templates/_layout.html.twig
  templates/_navbar.html.twig
Labels: Reviewed

#189 Routes vides
  src/Controller/DocumentController.php
  src/Controller/HomeController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  templates/_footer.html.twig
  templates/_layout.html.twig
  templates/_navbar.html.twig
  templates/home/index.html.twig
  templates/home/notImplemented.html.twig
  templates/lawyer/index.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#191 fix update profil
  src/Entity/Person.php
  src/Entity/User.php
  src/Form/UserType.php
Labels: Reviewed

#192 fix route security for field
  src/Controller/DocumentController.php
  src/Controller/FieldController.php
Labels: Corrections done

#190 fix sidebar hardcoding
  src/DataFixtures/UserFixtures.php
  templates/_layout.html.twig
Labels: Conflicts resolved

#196 Correction footer volant
  assets/scss/app.scss
Labels: Reviewed

#195 Modification des textes des boutons sur la page article
  assets/scss/article.scss
  templates/article/_form.html.twig
  templates/article/edit.html.twig
  templates/article/new.html.twig
Labels: Reviewed

#197 FixSaveBtn
  assets/scss/document.scss
  templates/dashboard/Admin/document/editor.html.twig
Labels: Reviewed

#198 Fix Security Assert Max Nb PhoneNumber PersonEntity
  src/Entity/Person.php
Labels: Reviewed

#199 Fixing article asserts message
  src/Entity/Article.php
  symfony.lock
Labels: Reviewed

#200 fixBreakWord
  assets/scss/dashboardPage.scss
Labels: Reviewed

#201 Fixing lawyer access
  src/Controller/LawyerController.php
Labels: Reviewed

#202 Fixing Validation Registration Form
  src/Entity/Person.php
Labels: Reviewed

#203 Creation of fixture for Fields
  src/DataFixtures/FieldFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#205 fix margin EditDocu
  templates/dashboard/Admin/document/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#206 Logout remove
  templates/_layout.html.twig
Labels: Reviewed

#207 change textarea to text
  src/Form/ClientType.php
  src/Form/LawyerType.php
Labels: Reviewed

#204 Lawyer speciality card
  assets/scss/dashboardPage.scss
  templates/dashboard/index.html.twig
Labels: Reviewed

#208 fix UI article
  templates/article/index.html.twig
Labels: Reviewed

#209 validation phone number
  src/Entity/Person.php
Labels: Reviewed

#210 validation nom et prenom
  src/Entity/Person.php
Labels: Reviewed

#211 Fixing not implemented page
  templates/home/notImplemented.html.twig
Labels: Reviewed

#213 Add Jean Doe to Persons
  src/DataFixtures/PersonFixtures.php
Labels: Reviewed

#216 Configuration du Regex pour le Mot de passe
  src/Entity/User.php
Labels: Reviewed

#217 Address country delete from registration
  src/Controller/RegistrationController.php
  src/Entity/Person.php
  src/Entity/User.php
  src/Form/RegistrationUserType.php
  src/Form/UserType.php
  templates/registration/user.html.twig
Labels: Reviewed

#218 Suppresssion des partenaires
  templates/home/index.html.twig
Labels: Reviewed

#220 Mise à jour des stats sur les quizz gagnés
  README.md
Labels: Reviewed
